export const Theme = {
  colors: {
    primary: '#0058bd',
    secondary: '#006e2c',
    error: '#ba1a1a',
    background: '#fcf8f8',
    surface: '#fcf8f8',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#424753',
    surfaceContainerLow: '#f7f3f2',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerHigh: '#ebe7e7',
    surfaceContainerHighest: '#e5e2e1',
    primaryContainer: '#2771df',
    secondaryContainer: '#86f898',
    errorContainer: '#ffdad6',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
    onError: '#ffffff',
    onPrimaryContainer: '#fefcff',
    onSecondaryContainer: '#00722f',
    onTertiaryContainer: '#fffbff',
    outline: '#727785',
    outlineVariant: '#c2c6d5',
  },
  typography: {
    headline: 'PlusJakartaSans_700Bold',
    subHeadline: 'PlusJakartaSans_600SemiBold',
    body: 'Inter_400Regular',
    bodyMedium: 'Inter_500Medium',
    label: 'Inter_600SemiBold',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 24,
    full: 9999,
  }
};
